"""Constants module."""

from .common import get_local_iso_date, get_session_start_date, get_local_month_year
from .spinner_verbs import SPINNER_VERBS, get_spinner_verbs
from .messages import NO_CONTENT_MESSAGE
from .figures import (
    BLACK_CIRCLE,
    BULLET_OPERATOR,
    TEARDROP_ASTERISK,
    UP_ARROW,
    DOWN_ARROW,
    LIGHTNING_BOLT,
    EFFORT_LOW,
    EFFORT_MEDIUM,
    EFFORT_HIGH,
    EFFORT_MAX,
    PLAY_ICON,
    PAUSE_ICON,
    REFRESH_ARROW,
    CHANNEL_ARROW,
    INJECTED_ARROW,
    FORK_GLYPH,
    DIAMOND_OPEN,
    DIAMOND_FILLED,
    REFERENCE_MARK,
    FLAG_ICON,
    BLOCKQUOTE_BAR,
    HEAVY_HORIZONTAL,
    BRIDGE_SPINNER_FRAMES,
    BRIDGE_READY_INDICATOR,
    BRIDGE_FAILED_INDICATOR,
)
from .api_limits import (
    API_IMAGE_MAX_BASE64_SIZE,
    IMAGE_TARGET_RAW_SIZE,
    IMAGE_MAX_WIDTH,
    IMAGE_MAX_HEIGHT,
    PDF_TARGET_RAW_SIZE,
    API_PDF_MAX_PAGES,
    PDF_EXTRACT_SIZE_THRESHOLD,
    PDF_MAX_EXTRACT_SIZE,
    PDF_MAX_PAGES_PER_READ,
    PDF_AT_MENTION_INLINE_THRESHOLD,
    API_MAX_MEDIA_PER_REQUEST,
)

__all__ = [
    # common
    'get_local_iso_date',
    'get_session_start_date',
    'get_local_month_year',
    # spinner_verbs
    'SPINNER_VERBS',
    'get_spinner_verbs',
    # messages
    'NO_CONTENT_MESSAGE',
    # figures
    'BLACK_CIRCLE',
    'BULLET_OPERATOR',
    'TEARDROP_ASTERISK',
    'UP_ARROW',
    'DOWN_ARROW',
    'LIGHTNING_BOLT',
    'EFFORT_LOW',
    'EFFORT_MEDIUM',
    'EFFORT_HIGH',
    'EFFORT_MAX',
    'PLAY_ICON',
    'PAUSE_ICON',
    'REFRESH_ARROW',
    'CHANNEL_ARROW',
    'INJECTED_ARROW',
    'FORK_GLYPH',
    'DIAMOND_OPEN',
    'DIAMOND_FILLED',
    'REFERENCE_MARK',
    'FLAG_ICON',
    'BLOCKQUOTE_BAR',
    'HEAVY_HORIZONTAL',
    'BRIDGE_SPINNER_FRAMES',
    'BRIDGE_READY_INDICATOR',
    'BRIDGE_FAILED_INDICATOR',
    # api_limits
    'API_IMAGE_MAX_BASE64_SIZE',
    'IMAGE_TARGET_RAW_SIZE',
    'IMAGE_MAX_WIDTH',
    'IMAGE_MAX_HEIGHT',
    'PDF_TARGET_RAW_SIZE',
    'API_PDF_MAX_PAGES',
    'PDF_EXTRACT_SIZE_THRESHOLD',
    'PDF_MAX_EXTRACT_SIZE',
    'PDF_MAX_PAGES_PER_READ',
    'PDF_AT_MENTION_INLINE_THRESHOLD',
    'API_MAX_MEDIA_PER_REQUEST',
]