"""GitHub App constants."""

GITHUB_APP_NAME = "Claude Code"
GITHUB_APP_URL = "https://github.com/apps/claude-code"

# Permissions
PERMISSION_CONTENTS = "contents"
PERMISSION_ISSUES = "issues"
PERMISSION_PULL_REQUESTS = "pull_requests"
PERMISSION_REPOS = "repo"

REQUIRED_PERMISSIONS = [
    PERMISSION_CONTENTS,
    PERMISSION_REPOS,
]


__all__ = [
    'GITHUB_APP_NAME',
    'GITHUB_APP_URL',
    'PERMISSION_CONTENTS',
    'PERMISSION_ISSUES',
    'PERMISSION_PULL_REQUESTS',
    'PERMISSION_REPOS',
    'REQUIRED_PERMISSIONS',
]